'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.17929
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
'
Namespace MessageGateway
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MessageGatewayServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MessageGatewayService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendMessageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegisterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private NotifyStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MessageCenter.My.MySettings.Default.MessageCenter_MessageGateway_MessageGatewayService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendMessageCompleted As SendMessageCompletedEventHandler
        
        '''<remarks/>
        Public Event RegisterCompleted As RegisterCompletedEventHandler
        
        '''<remarks/>
        Public Event NotifyStatusCompleted As NotifyStatusCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("SendMessage", RequestNamespace:="", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function SendMessage(ByVal Usercode As String, ByVal Password As String, ByVal Recipients As String, ByVal MessageType As Integer, ByVal Title As String, ByVal Content As String, ByVal Format As Integer, ByVal RetryOnError As Boolean, ByVal Reportflag As Integer, ByVal MessageID As String) As Integer
            Dim results() As Object = Me.Invoke("SendMessage", New Object() {Usercode, Password, Recipients, MessageType, Title, Content, Format, RetryOnError, Reportflag, MessageID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMessageAsync(ByVal Usercode As String, ByVal Password As String, ByVal Recipients As String, ByVal MessageType As Integer, ByVal Title As String, ByVal Content As String, ByVal Format As Integer, ByVal RetryOnError As Boolean, ByVal Reportflag As Integer, ByVal MessageID As String)
            Me.SendMessageAsync(Usercode, Password, Recipients, MessageType, Title, Content, Format, RetryOnError, Reportflag, MessageID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMessageAsync(ByVal Usercode As String, ByVal Password As String, ByVal Recipients As String, ByVal MessageType As Integer, ByVal Title As String, ByVal Content As String, ByVal Format As Integer, ByVal RetryOnError As Boolean, ByVal Reportflag As Integer, ByVal MessageID As String, ByVal userState As Object)
            If (Me.SendMessageOperationCompleted Is Nothing) Then
                Me.SendMessageOperationCompleted = AddressOf Me.OnSendMessageOperationCompleted
            End If
            Me.InvokeAsync("SendMessage", New Object() {Usercode, Password, Recipients, MessageType, Title, Content, Format, RetryOnError, Reportflag, MessageID}, Me.SendMessageOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMessageOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMessageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMessageCompleted(Me, New SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("Register", RequestNamespace:="", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function Register(ByVal Usercode As String, ByVal Password As String, ByVal CallBackAddr As String) As Integer
            Dim results() As Object = Me.Invoke("Register", New Object() {Usercode, Password, CallBackAddr})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegisterAsync(ByVal Usercode As String, ByVal Password As String, ByVal CallBackAddr As String)
            Me.RegisterAsync(Usercode, Password, CallBackAddr, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegisterAsync(ByVal Usercode As String, ByVal Password As String, ByVal CallBackAddr As String, ByVal userState As Object)
            If (Me.RegisterOperationCompleted Is Nothing) Then
                Me.RegisterOperationCompleted = AddressOf Me.OnRegisterOperationCompleted
            End If
            Me.InvokeAsync("Register", New Object() {Usercode, Password, CallBackAddr}, Me.RegisterOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegisterOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegisterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegisterCompleted(Me, New RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function NotifyStatus(ByVal MessageID As String, ByVal Recipients As String, ByVal NotifyType As Integer, ByVal Status As Integer, ByVal Text As String, ByVal Param As Object) As Integer
            Dim results() As Object = Me.Invoke("NotifyStatus", New Object() {MessageID, Recipients, NotifyType, Status, Text, Param})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub NotifyStatusAsync(ByVal MessageID As String, ByVal Recipients As String, ByVal NotifyType As Integer, ByVal Status As Integer, ByVal Text As String, ByVal Param As Object)
            Me.NotifyStatusAsync(MessageID, Recipients, NotifyType, Status, Text, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub NotifyStatusAsync(ByVal MessageID As String, ByVal Recipients As String, ByVal NotifyType As Integer, ByVal Status As Integer, ByVal Text As String, ByVal Param As Object, ByVal userState As Object)
            If (Me.NotifyStatusOperationCompleted Is Nothing) Then
                Me.NotifyStatusOperationCompleted = AddressOf Me.OnNotifyStatusOperationCompleted
            End If
            Me.InvokeAsync("NotifyStatus", New Object() {MessageID, Recipients, NotifyType, Status, Text, Param}, Me.NotifyStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnNotifyStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.NotifyStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NotifyStatusCompleted(Me, New NotifyStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub SendMessageCompletedEventHandler(ByVal sender As Object, ByVal e As SendMessageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMessageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RegisterCompletedEventHandler(ByVal sender As Object, ByVal e As RegisterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegisterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub NotifyStatusCompletedEventHandler(ByVal sender As Object, ByVal e As NotifyStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class NotifyStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
