'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.17929
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
'
Namespace MessageCenterservice
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MessageCenterServiceSoap", [Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Parameter()))>  _
    Partial Public Class MessageCenterService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendMessageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private NotifyStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EchoOfSendSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecieveMessageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.EMP.My.MySettings.Default.EMP_Client_DesktopClient_MessageCenterservice_MessageCenterService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendMessageCompleted As SendMessageCompletedEventHandler
        
        '''<remarks/>
        Public Event NotifyStatusCompleted As NotifyStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event EchoOfSendSMSCompleted As EchoOfSendSMSCompletedEventHandler
        
        '''<remarks/>
        Public Event RecieveMessageCompleted As RecieveMessageCompletedEventHandler
        
        '''<remarks/>
        Public Event LoginCompleted As LoginCompletedEventHandler
        
        '''<remarks/>
        Public Event getDataCompleted As getDataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("SendMessage", RequestNamespace:="", ResponseNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function SendMessage( _
                    ByVal CONNID As String,  _
                    ByVal NodeID As String,  _
                    ByVal NodeUsercode As String,  _
                    ByVal NodePassword As String,  _
                    ByVal Usercode As String,  _
                    ByVal Password As String,  _
                    ByVal Sender As String,  _
                    ByVal SenderName As String,  _
                    ByVal Recipients As String,  _
                    ByVal CC As String,  _
                    ByVal Bcc As String,  _
                    ByVal MessageType As Integer,  _
                    ByVal Title As String,  _
                    ByVal Content As String,  _
                    ByVal Format As Integer,  _
                    ByVal RetryOnError As Boolean,  _
                    ByVal Reportflag As Integer,  _
                    ByVal MessageID As String,  _
                    ByVal InterfaceID As String,  _
                    ByVal Param As String) As Integer
            Dim results() As Object = Me.Invoke("SendMessage", New Object() {CONNID, NodeID, NodeUsercode, NodePassword, Usercode, Password, Sender, SenderName, Recipients, CC, Bcc, MessageType, Title, Content, Format, RetryOnError, Reportflag, MessageID, InterfaceID, Param})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMessageAsync( _
                    ByVal CONNID As String,  _
                    ByVal NodeID As String,  _
                    ByVal NodeUsercode As String,  _
                    ByVal NodePassword As String,  _
                    ByVal Usercode As String,  _
                    ByVal Password As String,  _
                    ByVal Sender As String,  _
                    ByVal SenderName As String,  _
                    ByVal Recipients As String,  _
                    ByVal CC As String,  _
                    ByVal Bcc As String,  _
                    ByVal MessageType As Integer,  _
                    ByVal Title As String,  _
                    ByVal Content As String,  _
                    ByVal Format As Integer,  _
                    ByVal RetryOnError As Boolean,  _
                    ByVal Reportflag As Integer,  _
                    ByVal MessageID As String,  _
                    ByVal InterfaceID As String,  _
                    ByVal Param As String)
            Me.SendMessageAsync(CONNID, NodeID, NodeUsercode, NodePassword, Usercode, Password, Sender, SenderName, Recipients, CC, Bcc, MessageType, Title, Content, Format, RetryOnError, Reportflag, MessageID, InterfaceID, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMessageAsync( _
                    ByVal CONNID As String,  _
                    ByVal NodeID As String,  _
                    ByVal NodeUsercode As String,  _
                    ByVal NodePassword As String,  _
                    ByVal Usercode As String,  _
                    ByVal Password As String,  _
                    ByVal Sender As String,  _
                    ByVal SenderName As String,  _
                    ByVal Recipients As String,  _
                    ByVal CC As String,  _
                    ByVal Bcc As String,  _
                    ByVal MessageType As Integer,  _
                    ByVal Title As String,  _
                    ByVal Content As String,  _
                    ByVal Format As Integer,  _
                    ByVal RetryOnError As Boolean,  _
                    ByVal Reportflag As Integer,  _
                    ByVal MessageID As String,  _
                    ByVal InterfaceID As String,  _
                    ByVal Param As String,  _
                    ByVal userState As Object)
            If (Me.SendMessageOperationCompleted Is Nothing) Then
                Me.SendMessageOperationCompleted = AddressOf Me.OnSendMessageOperationCompleted
            End If
            Me.InvokeAsync("SendMessage", New Object() {CONNID, NodeID, NodeUsercode, NodePassword, Usercode, Password, Sender, SenderName, Recipients, CC, Bcc, MessageType, Title, Content, Format, RetryOnError, Reportflag, MessageID, InterfaceID, Param}, Me.SendMessageOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMessageOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMessageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMessageCompleted(Me, New SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("NotifyStatus", RequestNamespace:="", ResponseNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function NotifyStatus(ByVal Reciver As String, ByVal SequenceNo As String, ByVal MessageID As String, ByVal Recipient As String, ByVal NotifyType As Integer, ByVal Status As Integer, ByVal Text As String, ByRef Reserve As String) As Integer
            Dim results() As Object = Me.Invoke("NotifyStatus", New Object() {Reciver, SequenceNo, MessageID, Recipient, NotifyType, Status, Text, Reserve})
            Reserve = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub NotifyStatusAsync(ByVal Reciver As String, ByVal SequenceNo As String, ByVal MessageID As String, ByVal Recipient As String, ByVal NotifyType As Integer, ByVal Status As Integer, ByVal Text As String, ByVal Reserve As String)
            Me.NotifyStatusAsync(Reciver, SequenceNo, MessageID, Recipient, NotifyType, Status, Text, Reserve, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub NotifyStatusAsync(ByVal Reciver As String, ByVal SequenceNo As String, ByVal MessageID As String, ByVal Recipient As String, ByVal NotifyType As Integer, ByVal Status As Integer, ByVal Text As String, ByVal Reserve As String, ByVal userState As Object)
            If (Me.NotifyStatusOperationCompleted Is Nothing) Then
                Me.NotifyStatusOperationCompleted = AddressOf Me.OnNotifyStatusOperationCompleted
            End If
            Me.InvokeAsync("NotifyStatus", New Object() {Reciver, SequenceNo, MessageID, Recipient, NotifyType, Status, Text, Reserve}, Me.NotifyStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnNotifyStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.NotifyStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NotifyStatusCompleted(Me, New NotifyStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("EchoOfSendSMS", RequestNamespace:="", ResponseNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function EchoOfSendSMS(ByVal Reciver As String, ByVal SequenceNo As String, ByVal MessageID As String, ByVal Recipient As String, ByVal Status As Integer, ByVal ErrorCode As Integer, ByRef Reserve As String) As Integer
            Dim results() As Object = Me.Invoke("EchoOfSendSMS", New Object() {Reciver, SequenceNo, MessageID, Recipient, Status, ErrorCode, Reserve})
            Reserve = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EchoOfSendSMSAsync(ByVal Reciver As String, ByVal SequenceNo As String, ByVal MessageID As String, ByVal Recipient As String, ByVal Status As Integer, ByVal ErrorCode As Integer, ByVal Reserve As String)
            Me.EchoOfSendSMSAsync(Reciver, SequenceNo, MessageID, Recipient, Status, ErrorCode, Reserve, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EchoOfSendSMSAsync(ByVal Reciver As String, ByVal SequenceNo As String, ByVal MessageID As String, ByVal Recipient As String, ByVal Status As Integer, ByVal ErrorCode As Integer, ByVal Reserve As String, ByVal userState As Object)
            If (Me.EchoOfSendSMSOperationCompleted Is Nothing) Then
                Me.EchoOfSendSMSOperationCompleted = AddressOf Me.OnEchoOfSendSMSOperationCompleted
            End If
            Me.InvokeAsync("EchoOfSendSMS", New Object() {Reciver, SequenceNo, MessageID, Recipient, Status, ErrorCode, Reserve}, Me.EchoOfSendSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnEchoOfSendSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.EchoOfSendSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EchoOfSendSMSCompleted(Me, New EchoOfSendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("RecieveMessage", RequestNamespace:="", ResponseNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function RecieveMessage(ByVal Reciver As String, ByVal SequenceNo As String, ByVal Recipients As String, ByVal From As String, ByVal Sender As String, ByVal Title As String, ByVal Content As String, ByVal Format As Integer, ByVal RecieveTime As Date) As Integer
            Dim results() As Object = Me.Invoke("RecieveMessage", New Object() {Reciver, SequenceNo, Recipients, From, Sender, Title, Content, Format, RecieveTime})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecieveMessageAsync(ByVal Reciver As String, ByVal SequenceNo As String, ByVal Recipients As String, ByVal From As String, ByVal Sender As String, ByVal Title As String, ByVal Content As String, ByVal Format As Integer, ByVal RecieveTime As Date)
            Me.RecieveMessageAsync(Reciver, SequenceNo, Recipients, From, Sender, Title, Content, Format, RecieveTime, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecieveMessageAsync(ByVal Reciver As String, ByVal SequenceNo As String, ByVal Recipients As String, ByVal From As String, ByVal Sender As String, ByVal Title As String, ByVal Content As String, ByVal Format As Integer, ByVal RecieveTime As Date, ByVal userState As Object)
            If (Me.RecieveMessageOperationCompleted Is Nothing) Then
                Me.RecieveMessageOperationCompleted = AddressOf Me.OnRecieveMessageOperationCompleted
            End If
            Me.InvokeAsync("RecieveMessage", New Object() {Reciver, SequenceNo, Recipients, From, Sender, Title, Content, Format, RecieveTime}, Me.RecieveMessageOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecieveMessageOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecieveMessageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecieveMessageCompleted(Me, New RecieveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("Login", RequestNamespace:="", ResponseNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function Login(ByVal Usercode As String, ByVal Password As String, ByVal Version As String, ByVal TerminalID As String, ByVal IPAddress As String, ByVal ComputerName As String, ByVal MAC As String, ByVal CPUID As String, ByVal DISKID As String) As String
            Dim results() As Object = Me.Invoke("Login", New Object() {Usercode, Password, Version, TerminalID, IPAddress, ComputerName, MAC, CPUID, DISKID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal Usercode As String, ByVal Password As String, ByVal Version As String, ByVal TerminalID As String, ByVal IPAddress As String, ByVal ComputerName As String, ByVal MAC As String, ByVal CPUID As String, ByVal DISKID As String)
            Me.LoginAsync(Usercode, Password, Version, TerminalID, IPAddress, ComputerName, MAC, CPUID, DISKID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal Usercode As String, ByVal Password As String, ByVal Version As String, ByVal TerminalID As String, ByVal IPAddress As String, ByVal ComputerName As String, ByVal MAC As String, ByVal CPUID As String, ByVal DISKID As String, ByVal userState As Object)
            If (Me.LoginOperationCompleted Is Nothing) Then
                Me.LoginOperationCompleted = AddressOf Me.OnLoginOperationCompleted
            End If
            Me.InvokeAsync("Login", New Object() {Usercode, Password, Version, TerminalID, IPAddress, ComputerName, MAC, CPUID, DISKID}, Me.LoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoginCompleted(Me, New LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xxyj6450.s181.288idc.com/WebService.asmx/getData", RequestNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", ResponseNamespace:="http://xxyj6450.s181.288idc.com/WebService.asmx", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getData(ByVal Usercode As String, ByVal Password As String, ByVal QueryString As Command) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getData", New Object() {Usercode, Password, QueryString})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDataAsync(ByVal Usercode As String, ByVal Password As String, ByVal QueryString As Command)
            Me.getDataAsync(Usercode, Password, QueryString, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDataAsync(ByVal Usercode As String, ByVal Password As String, ByVal QueryString As Command, ByVal userState As Object)
            If (Me.getDataOperationCompleted Is Nothing) Then
                Me.getDataOperationCompleted = AddressOf Me.OngetDataOperationCompleted
            End If
            Me.InvokeAsync("getData", New Object() {Usercode, Password, QueryString}, Me.getDataOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDataCompleted(Me, New getDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx")>  _
    Partial Public Class Command
        
        Private commandTextField As String
        
        Private commandTypeField As System.Data.CommandType
        
        Private parametersField() As Parameter
        
        '''<remarks/>
        Public Property CommandText() As String
            Get
                Return Me.commandTextField
            End Get
            Set
                Me.commandTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CommandType() As System.Data.CommandType
            Get
                Return Me.commandTypeField
            End Get
            Set(value As System.Data.CommandType)
                Me.commandTypeField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Parameters() As Parameter()
            Get
                Return Me.parametersField
            End Get
            Set
                Me.parametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx")>  _
    Public Enum CommandType
        
        '''<remarks/>
        Text
        
        '''<remarks/>
        StoredProcedure
        
        '''<remarks/>
        TableDirect
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx")>  _
    Partial Public Class Parameter
        
        Private directionField As System.Data.ParameterDirection
        
        Private sourceVersionField As System.Data.DataRowVersion
        
        Private sourceColumnField As String
        
        Private nameField As String
        
        Private typeField As System.Data.SqlDbType
        
        Private valueField As Object
        
        '''<remarks/>
        Public Property Direction() As System.Data.ParameterDirection
            Get
                Return Me.directionField
            End Get
            Set(value As System.Data.ParameterDirection)
                Me.directionField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SourceVersion() As System.Data.DataRowVersion
            Get
                Return Me.sourceVersionField
            End Get
            Set(value As System.Data.DataRowVersion)
                Me.sourceVersionField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SourceColumn() As String
            Get
                Return Me.sourceColumnField
            End Get
            Set
                Me.sourceColumnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As System.Data.SqlDbType
            Get
                Return Me.typeField
            End Get
            Set(value As System.Data.SqlDbType)
                Me.typeField = Value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx")>  _
    Public Enum ParameterDirection
        
        '''<remarks/>
        Input
        
        '''<remarks/>
        Output
        
        '''<remarks/>
        InputOutput
        
        '''<remarks/>
        ReturnValue
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx")>  _
    Public Enum DataRowVersion
        
        '''<remarks/>
        Original
        
        '''<remarks/>
        Current
        
        '''<remarks/>
        Proposed
        
        '''<remarks/>
        [Default]
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xxyj6450.s181.288idc.com/WebService.asmx")>  _
    Public Enum SqlDbType
        
        '''<remarks/>
        BigInt
        
        '''<remarks/>
        Binary
        
        '''<remarks/>
        Bit
        
        '''<remarks/>
        [Char]
        
        '''<remarks/>
        DateTime
        
        '''<remarks/>
        [Decimal]
        
        '''<remarks/>
        Float
        
        '''<remarks/>
        Image
        
        '''<remarks/>
        Int
        
        '''<remarks/>
        Money
        
        '''<remarks/>
        NChar
        
        '''<remarks/>
        NText
        
        '''<remarks/>
        NVarChar
        
        '''<remarks/>
        Real
        
        '''<remarks/>
        UniqueIdentifier
        
        '''<remarks/>
        SmallDateTime
        
        '''<remarks/>
        SmallInt
        
        '''<remarks/>
        SmallMoney
        
        '''<remarks/>
        Text
        
        '''<remarks/>
        Timestamp
        
        '''<remarks/>
        TinyInt
        
        '''<remarks/>
        VarBinary
        
        '''<remarks/>
        VarChar
        
        '''<remarks/>
        [Variant]
        
        '''<remarks/>
        Xml
        
        '''<remarks/>
        Udt
        
        '''<remarks/>
        Structured
        
        '''<remarks/>
        [Date]
        
        '''<remarks/>
        Time
        
        '''<remarks/>
        DateTime2
        
        '''<remarks/>
        DateTimeOffset
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub SendMessageCompletedEventHandler(ByVal sender As Object, ByVal e As SendMessageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMessageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub NotifyStatusCompletedEventHandler(ByVal sender As Object, ByVal e As NotifyStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class NotifyStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Reserve() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EchoOfSendSMSCompletedEventHandler(ByVal sender As Object, ByVal e As EchoOfSendSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EchoOfSendSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Reserve() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub RecieveMessageCompletedEventHandler(ByVal sender As Object, ByVal e As RecieveMessageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecieveMessageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub LoginCompletedEventHandler(ByVal sender As Object, ByVal e As LoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getDataCompletedEventHandler(ByVal sender As Object, ByVal e As getDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
